sudo: required
services:
    - docker
    
before_install:
    - docker build -t nymphosis/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true nymphosis/docker-react npm run test -- --coverage

language: generic 